### ISSUE TITLE
Webfonts

### ISSUE THREAD

**Issue by halfempty** [clockshop/the-tie-that-binds#1]
Tom, 

In general, self-hosted is preferred ‘cause it means we can write the CSS in a very straightforward way, give things very simple names and easy call on weights and styles. It’s nice. BUT! In this case they’re selling that as a high-cost premium option, so “subscription” will be totally fine for our project. 

The domain for the license will be the-tie-that-binds.org

If Amanda’s amenable, you might ask her if she could take over the license for the renewal. She seems pretty on top of that stuff, and that would keep you from having to ping them next year with a bill for it. (But that’s really up to you. Everyone has their own way of handling that kind of stuff, I think.)

**Comment by tkracauer** [comment]
Okay, I'll reach out to Amanda in regards to this stuff. And thanks for the advice and confirming the web address.

**Comment by tkracauer** [comment]
For the time being, you could use Open Sans Light. Idk if its too much trouble later to swap the prefered font in (I know it can be for print design). 

https://www.google.com/fonts/specimen/Open+Sans

**Comment by tkracauer** [comment]
Amanda remarked that she wants to use the fonts i've specified but she worries about the yearly fee. She said she may forget to pay it in the future. Is it possible to have a backup font that swaps itself in if Agipo is made unavailable?

**Comment by halfempty** [comment]
@tkracauer It's automatic to fall back to a web default, such as Helvetica. 

(I's technically possible to also fall back to something like a free one from Google but it's not really a good idea to do so. Would slowdown page load times and there's a high probability it would break in a couple of years w/o maintenance anyhow)

**Comment by tkracauer** [comment]
@halfempty 
Thanks for the info Marty, whatever you think is lightest and best.

**Comment by tkracauer** [comment]
Marty—The email from the foundry

We have set up the web font service for your website. It includes subscription license for:

Agipo Light
Agipo Light Italic
Agipo Regular
Agipo Bold

and is accessible only to pages hosted under the domains of 

the-tie-that-binds.org

(and all of its subdomains, plus in development via localhost at http://127.0.0.1). If you wish to add support for more domains, please let us know.

You can use the service by including this line in the head section of your website:

<link href="//webfonts.radimpesko.com/RP-W-576b928d80f5d7020f00002e.css" rel="stylesheet" type="text/css">

The font can be then used by specifying it in your styles as follows:

font-family:  'Agipo Light';
font-weight:  normal;
font-style:   normal;
font-stretch: normal;

font-family:  'Agipo Light Italic';
font-weight:  normal;
font-style:   italic;
font-stretch: normal;

font-family:  'Agipo Regular';
font-weight:  normal;
font-style:   normal;
font-stretch: normal;

font-family:  'Agipo Bold';
font-weight:  bold;
font-style:   normal;
font-stretch: normal;

Again, the service is currently in testing mode, and will be launched fully soon. We will send you invoice for the license then.

We would be grateful for any feedback regarding the performance of the service. Please also do not hesitate to let us know if you have any questions or encounter any issues.

Best wishes,
Tomas & Radim

**Comment by halfempty** [comment]
@tkracauer Thanks! Got the embed working. Will close this thread.

**Comment by tkracauer** [comment]
@halfempty great! I'm sure the foundry would appreciate any comments/feedback from you if you have any.
