### ISSUE TITLE
Various underlines

### ISSUE THREAD

**Issue by halfempty** [clockshop/the-tie-that-binds#2]
@tkracauer 

Hey Tom, wanted to touch-base about the best way to do underlines in various spots. I'll details some of the CSS involved so that I can get your opinion on the best techniques to use.

**Headings**

![image](https://cloud.githubusercontent.com/assets/775543/16570058/01f8a992-4204-11e6-8738-c4badcce9e1a.png)

The comps have the drop shadow applied to the underline as well as the text. CSS doesn't give us a way to apply this in any kind of natural way. I can imagine a hack that might possibly work (having the underline actually be a rectangular element that's precisely positioned) but it's something I'll only try if this shadow is important, in your opinion. What we're seeing now is what CSS gives us for free. Thoughts?

**"Underline" vs. "Border-bottom"**

CSS gives us two ways to draw underlines on text, "Underline" and "Border-bottom."

Underline is drawn relatively close to the bottom of the letters. The color is inherited from the letters themselves and can't be controlled independently. The stroke thickness is set automatically based on the size of the text. Example:

![image](https://cloud.githubusercontent.com/assets/775543/16570143/8993b95e-4205-11e6-9544-ee925bfbd391.png)

Border-bottom is drawn according to the line-height / leading, usually resulting in it being further from the letters. We do have control over the color and the stroke:

![image](https://cloud.githubusercontent.com/assets/775543/16570174/36638bbe-4206-11e6-874c-a56a50a3eb5e.png)

Have a preference? Whichever way we go, I'm thinking we should be consistent across different elements. Here's the footer in the two styles:

Underline:
![image](https://cloud.githubusercontent.com/assets/775543/16570159/f86c06b0-4205-11e6-8035-98678001f687.png)

Border-bottom:
![image](https://cloud.githubusercontent.com/assets/775543/16570163/062b75ce-4206-11e6-9eed-5ea58bd5fe4f.png)

**Comment by tkracauer** [comment]
Hi Marty

Thanks for breaking this down for me. The option for bottom-border looks better to me. The drop shadow in the headline is not crucial. Don't trouble over it. 

All the best
Tom

**Comment by halfempty** [comment]
@tkracauer Thanks!
