### ISSUE TITLE
Infini webfont

### ISSUE THREAD

**Issue by halfempty** [clockshop/the-tie-that-binds#3]
@tkracauer So far I'm noticing only one instance of the Infini font as text (outside of what will be formatted as graphics/images), and that's here in the captions for the plant images:

![image](https://cloud.githubusercontent.com/assets/775543/16570752/971d6dc0-4211-11e6-99ef-f6e52a34cb00.png)

If this is the only instance, would it be cool to use Agipo here, as we're doing on image captions elsewhere? And refrain from loading Infini as a webfont?

**Comment by tkracauer** [comment]
Hi Marty

I'd prefer to have this instance of Infini remain as the italic for Agipo is more a slant and not an italic. 

Tk

**Comment by halfempty** [comment]
@tkracauer Got it!
