### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by tkracauer** [clockshop/the-tie-that-binds#4]
@halfempty 

New Logo file uploaded to the dropbox. Please implement when you have a chance.

Tk

**Comment by halfempty** [comment]
@tkracauer Logo update looks good. It's the stencil lines, right?

(Btw I'm going to move the Manual discussion to another thread, keep this one about the logo update)

**Comment by halfempty** [comment]
Done

**Comment by tkracauer** [comment]
@halfempty

Thanks, Marty.
