### ISSUE TITLE
Website Manual

### ISSUE THREAD

**Issue by halfempty** [clockshop/the-tie-that-binds#5]
@tkracauer said:

> Site looks fabulous, Marty! Excited to see it with real content. Do you provide a step by step PDF to clients to teach them how to use the site?

**Comment by halfempty** [comment]
@tkracauer Sometimes I provide that kind of a manual, but not in all cases. Given our budget on this project, as well as the relative simplicity of this site, I wasn't planning on it. 

I wonder if a Skype session, where we step through some of the procedures, would suffice?

**Comment by tkracauer** [comment]
@halfempty Sounds good to me. I suppose that should happen soon.
