### ISSUE TITLE
Editing the footer

### ISSUE THREAD

**Issue by tkracauer** [clockshop/the-tie-that-binds#7]
@halfempty 

Noticed a typo in the credits footer. Could you tell me where i go to edit this?

Thanks

**Comment by halfempty** [comment]
@tkracauer The footer's actually not content-editable. It can be made so but not easily. Easiest to tell me the error and I'll fix!

**Comment by tkracauer** [comment]
@halfempty 

Right column: The Tie that Binds: The Mirror of the Future is made possible by the support of the Department of **Cultureal** Affairs, The City of Los Angeles, Bloomberg Philanthropies, and the Ralph M. Parsons Foundation.

**Comment by halfempty** [comment]
@tkracauer Got it! And "affairs" was off in the middle column as well, so fixed that

**Comment by tkracauer** [comment]
@halfempty 
Double great!

Just a heads up....I WROTE THAT TEXT. I wouldn't at all be surprised if 11th hour they need changes made to that.....
