### ISSUE TITLE
Mobile scale

### ISSUE THREAD

**Issue by halfempty** [clockshop/the-tie-that-binds#8]
@tkracauer Hey Tom, my InDesign is opening the mobile mock-ups at a crazy-big size, 1242px across. I encountered something like this once before, and addressed it by rescaling the units. 

What size should I scale it to? 50%? Something more specific? (What was your target?)

**Comment by tkracauer** [comment]
Hi Marty

That file was set up by taking a screenshot of my iPhone then determining the pixel width from photoshop. Could be totally the wrong way to do this, but a percentage to scale from is hard to say. Can this be done visually? Ie the width of the mockup shows proportionately what size things should be.

**Comment by halfempty** [comment]
@tkracauer What phone do you have? 

This is one of those things that used to be totally simple but is now complicated. Here's a breakdown of iPhone resolutions: 

https://www.paintcodeapp.com/news/ultimate-guide-to-iphone-resolutions

**Comment by tkracauer** [comment]
I have iPhone 6plus, does that help?

Tk

**Comment by halfempty** [comment]
@tkracauer Yes, thanks!

**Comment by halfempty** [comment]
@tkracauer Okay, so.. The mockup is three times the intended size. This means text that's measuring as 85.05px really needs to be 28.35px. 

We need to find a way to resize the entire doc. Do you know of one?

**Comment by tkracauer** [comment]
@halfempty I only know of the hard way. Does that absolutely need to be done in order for you to size the typography?

Probably not a huge task, its just resizing the type in all unique instances, yes?

Will take care of it tonight and resend a new INDD doc with sizes changed!

**Comment by halfempty** [comment]
@tkracauer Thanks man!

**Comment by tkracauer** [comment]
@halfempty 

A new mobile doc is now in the dropbox!

**Comment by halfempty** [comment]
@tkracauer Thank you! Very much appreciated

**Comment by halfempty** [comment]
@tkracauer Would it be possible for you to add to that new doc examples of the block-types that aren't shown? These are, specifically:
- The "Page Header" title block used on Visit, etc;
- The "Large Text" block used on Visit, etc;
- ~~The "Big Map" block used on Visit;~~
- The "Garden" block used on Garden; and
- The "News" block used on News.

You wouldn't have to replicate the whole site, just single examples of each block-type would be fine.

I can extrapolate from the examples you've already given, but if you've a chance to take a look that would be super.

Edit: No need to do "Big Map," actually, there's really only one way it can go.

**Comment by tkracauer** [comment]
Hey @halfempty 

Thats uploading to the dropbox now. 

Is it too much trouble to move the title of the Plot in the Gardens section to above the images of the plants? I've been thinking that the beginning of that section seems a bit undefined the way it is now. 

I'll put in a PDF of the revise section in the dropbox too. 

tk

**Comment by halfempty** [comment]
@tkracauer Okay, I think the mobile breakpoints are in! In addition to the iPhone 6 sized-screen, I also put in breakpoints for the iPhone 5 screen, where the margins are brought in just a tad.

Take a look on your phone and let me know how it looks? (I've actually only looked via the emulator so-far, not my actual phone)

**Comment by tkracauer** [comment]
@halfempty 

Fabulous work, Marty. Looks great. Well done. 

tk
